In [2]:
import numpy as np
import pandas as pd
import torch
import os
import math
import util
from nbtschematic import SchematicFile
import schemfio
import schematic_data
from schematic_data import SchematicData

In [2]:
input = np.ones((2,3,4), dtype=np.uint16)
output = np.zeros((2,3,1), dtype=np.uint16)
util.np_to_blockdata(input, output, (2,'+'), 'test1.blockdata')
util.np_load_blockdata('test1.blockdata')

2
22
9
9
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
(2, 3, 4)
2
22
9
9
2
22
9
9


(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=uint16),
 array([[[0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0]]], dtype=uint16),
 (None, None))

In [5]:
arr = np.ones((6,5,5), dtype=np.uint8)
schemfio.write_ndarray(arr, './', 'test.tkn')

wrote test.tkn to ./


True

In [ ]:
SchematicData.

In [7]:
master_arr = np.zeros((2,2), dtype=np.uint16)
sub_arr = np.ones((2), dtype=np.uint16)
master_arr[0] = sub_arr
master_arr

array([[1, 1],
       [0, 0]], dtype=uint16)

In [23]:
nums = '3,3,3,3,0'
split = nums.split(',')
np.array(split, dtype=np.uint8)

array([3, 3, 3, 3, 0], dtype=uint8)

In [8]:
lines = ''
with open('test1.blockdata', 'r') as file:
    lines = file.readlines()
''.join(lines)

'input size:2,3,4\noutput size:2,3,1\ndim of continuity:2\ndir of continuity:+\n<>\n[\n[\n[\n1,1,1,1,\n],\n[\n1,1,1,1,\n],\n[\n1,1,1,1,\n],\n],\n[\n[\n1,1,1,1,\n],\n[\n1,1,1,1,\n],\n[\n1,1,1,1,\n],\n],\n],\n<>\n[\n[\n[\n0,\n],\n[\n0,\n],\n[\n0,\n],\n],\n[\n[\n0,\n],\n[\n0,\n],\n[\n0,\n],\n],\n],\n'

In [11]:
dims = (2,3,4)
total = 1
num_lines = 0
for dim in dims[:-2]:
    print(dim)
    num_lines += total * dim * 2
    total = total * dim
num_lines += total * dims[-2] * 3
print(num_lines)
# num_lines should be 24

2
22


In [32]:
split_rejoin = '2,4,5,6,7,8,9'
split_rejoin = split_rejoin.split(',')
print(split_rejoin)
split_rejoin = '\n'.join(split_rejoin)
print(split_rejoin)

['2', '4', '5', '6', '7', '8', '9']
2
4
5
6
7
8
9


In [5]:
nums = ['a','1','2']
nums = [x for x in nums if x.isdigit() ]
nums

['1', '2']

In [11]:
with open('test.txt', 'w') as f:
    f.write("test\ntest2")

In [12]:
with open('test.txt', 'r') as f:
    contents = f.readlines()
    print(contents)

['test\n', 'test2']


In [3]:
src_path = './data/schematics/'
dest_path = './data/block_arrays/arrays/scraped-batch-1/'
# print("wrote dateframe to ", dest_path)
block_arrays, filename_titles, all_mappings, schem_dims = schematic2matrix.GetBlockArraysFromDir(src_path, dest_path)
print("function done")

procesing  1.schematic
procesing  10.schematic
procesing  100.schematic
procesing  1000.schematic
procesing  10001.schematic
procesing  10002.schematic
procesing  10003.schematic
procesing  10005.schematic
procesing  10006.schematic
procesing  10007.schematic
procesing  10008.schematic
procesing  10009.schematic
procesing  1001.schematic
procesing  10010.schematic
procesing  10011.schematic
procesing  10012.schematic
procesing  10013.schematic
procesing  10014.schematic
procesing  10015.schematic
procesing  10016.schematic
procesing  10017.schematic
procesing  10018.schematic
procesing  10019.schematic
procesing  1002.schematic
procesing  10020.schematic
procesing  10021.schematic
procesing  10022.schematic
procesing  10023.schematic
procesing  10024.schematic
procesing  10025.schematic
procesing  10026.schematic
procesing  10027.schematic
procesing  10028.schematic
procesing  10029.schematic
procesing  1003.schematic
procesing  10030.schematic
procesing  10031.schematic
procesing  100

In [5]:
def schem_extractions_to_files(block_arrays, filename_titles, all_mappings, schem_dims):
    #with info, make universal mapping, convert all block arrays, make dataframe of file_of_origin, dest_file, dims; then write the converted block arrays to files
    block_tokens = util.get_blocks_tokenized(all_mappings)
    #make function for converting block array
    tokenized_schematics_blocks = []
    for i, blocks in enumerate(block_arrays):
        converted_blocks = np.array(blocks)
        converted_blocks = util.convert_blocks_to_mapping(blocks, all_mappings[i], block_tokens)
        tokenized_schematics_blocks.append(converted_blocks)

    #create the dataframe with: schematic_filename, tokenized_filename, dimensions
    tokenized_filenames = []
    for title in filename_titles:
        tokenized_filenames.append(title.removesuffix('schematic') + '.tkn')

    df_template = {'schematic_filename': filename_titles, 'tokenized_filenames' : tokenized_filenames, 'dimensions': schem_dims}
    df = pd.DataFrame(df_template)

    #write tokenized block array to files
    tokenized_path = './datasets/preliminary/tokenized_schems/'
    for i , blocks in enumerate(tokenized_schematics_blocks):
        util.write_tokenized_schematic_to_file(blocks, tokenized_path, tokenized_filenames[i])
    #write the dataframe to the parent directory
    
    df.to_csv('./datasets/preliminary/tokenized_schem_data.csv')
    print('Finished writing tokenized files and dataframe')

#--------------------------------------

In [24]:
def convert_blocks_to_mapping(blocks: np.ndarray, from_mapping: dict, to_mapping: dict) -> np.ndarray:
    conversion_mapping = {}
    for key in from_mapping.keys():
        conversion_mapping[int(from_mapping[key])] = int(to_mapping[key])
    print(conversion_mapping)
    for x in range(blocks.shape[0]):
        for y in range(blocks.shape[1]):
            for z in range(blocks.shape[2]):
                blocks[x,y,z] = conversion_mapping[blocks[x,y,z]]
    return blocks

In [27]:
# schem_extractions_to_files(block_arrays, filename_titles, all_mappings, schem_dims)
block_tokens = util.get_blocks_tokenized(all_mappings)
#make function for converting block array
block_tokens
print(block_arrays[0])
tokenized_schematics_blocks = []
for i, blocks in enumerate(block_arrays):
    converted_blocks = np.array(blocks)
    converted_blocks = convert_blocks_to_mapping(blocks, all_mappings[i], block_tokens)
    tokenized_schematics_blocks.append(converted_blocks)
    print('done')

[[[11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  ...
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]]

 [[11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  ...
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]]

 [[11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  ...
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]
  [11 11 11 ... 11 11 11]]

 ...

 [[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]]
{58: 0, 44

KeyError: 11

In [14]:
def convert_blocks_to_mapping(blocks: np.ndarray, from_mapping: dict, to_mapping: dict) -> np.ndarray:
    conversion_mapping = {}
    for key in from_mapping.keys():
        conversion_mapping[int(from_mapping[key])] = to_mapping[key]
    for x in range(blocks.shape[0]):
        for y in range(blocks.shape[1]):
            for z in range(blocks.shape[2]):
                blocks[x,y,z] = conversion_mapping[blocks[x,y,z]]
    return blocks

In [3]:
mappings

[{'minecraft:crafting_table': 58,
  'minecraft:stone_slab': 44,
  'minecraft:trapdoor': 96,
  'minecraft:stonebrick': 98,
  'minecraft:quartz_block': 155,
  'minecraft:sandstone_stairs': 128,
  'minecraft:fence': 85,
  'minecraft:furnace': 61,
  'minecraft:nether_brick': 112,
  'minecraft:water': 9,
  'minecraft:planks': 5,
  'minecraft:air': 0,
  'minecraft:oak_stairs': 53,
  'minecraft:glowstone': 89,
  'minecraft:torch': 50,
  'minecraft:log': 17,
  'minecraft:quartz_stairs': 156,
  'minecraft:wool': 35,
  'minecraft:bookshelf': 47,
  'minecraft:cobblestone': 4,
  'minecraft:stone_brick_stairs': 109,
  'minecraft:trapped_chest': 146,
  'minecraft:stone_stairs': 67,
  'minecraft:ladder': 65,
  'minecraft:skull': 144,
  'minecraft:chest': 54,
  'minecraft:sandstone': 24,
  'minecraft:leaves': 18,
  'minecraft:fence_gate': 107,
  'minecraft:nether_brick_stairs': 114},
 {'minecraft:tallgrass': 31,
  'minecraft:red_flower': 38,
  'minecraft:stained_glass': 95,
  'minecraft:lever': 69,
  

In [28]:
#get all mappings of block ids to nums
universal_mappings = {} # { id : list of nums}
for map in mappings:
    for key in map.keys():
        if not key in universal_mappings.keys():
            universal_mappings[key] = {map[key]: 1}
        elif map[key] not in universal_mappings[key].keys():
            universal_mappings[key][map[key]] = 1
        else:
            universal_mappings[key][map[key]] += 1

#find if there are keys for blocks, print them out
duplicate = False
keys = []
for key in universal_mappings.keys():
    if len(universal_mappings[key]) > 1:
        print(f'duplicate at {key}')
        keys.append(key)
        duplicate = True
print(duplicate)

for key in keys:
    print(f"{key} duplicates: ")
    print(universal_mappings[key])

#find if there are duplicate ids of any block to any id
ids = {} #ids to num of times theyre seen in universal mappings
for key in universal_mappings.keys():
    for subkey in universal_mappings[key].keys():
        if not subkey in ids:
            ids[subkey] = 1
        else:
            ids[subkey] += 1
print(ids)
print("Ones with duplicates:")
for key in ids.keys():
    if ids[key] > 1:
        print(f'{key}: {ids[key]}')
print('-------')


duplicate at minecraft:concrete
duplicate at minecraft:concrete_powder
duplicate at minecraft:magenta_glazed_terracotta
True
minecraft:concrete duplicates: 
{251: 285, 1093: 1, 467: 1, 416: 1}
minecraft:concrete_powder duplicates: 
{252: 59, 463: 1, 391: 1}
minecraft:magenta_glazed_terracotta duplicates: 
{238: 2, 237: 1}
{58: 1, 44: 1, 96: 1, 98: 1, 155: 1, 128: 1, 85: 1, 61: 1, 112: 1, 9: 1, 5: 1, 0: 1, 53: 1, 89: 1, 50: 1, 17: 1, 156: 1, 35: 1, 47: 1, 4: 1, 109: 1, 146: 1, 67: 1, 65: 1, 144: 1, 54: 1, 24: 1, 18: 1, 107: 1, 114: 1, 31: 1, 38: 1, 95: 1, 69: 1, 194: 1, 159: 1, 3: 1, 171: 1, 106: 1, 175: 1, 100: 1, 2: 1, 111: 1, 162: 1, 140: 1, 26: 1, 189: 1, 34: 1, 125: 1, 33: 1, 1: 1, 12: 1, 135: 1, 126: 1, 160: 1, 37: 1, 88: 1, 170: 1, 97: 1, 186: 1, 86: 1, 164: 1, 191: 1, 13: 1, 103: 1, 118: 1, 91: 1, 87: 1, 42: 1, 16: 1, 134: 1, 43: 1, 78: 1, 11: 1, 76: 1, 72: 1, 23: 1, 70: 1, 154: 1, 45: 1, 120: 1, 139: 1, 148: 1, 93: 1, 29: 1, 149: 1, 102: 1, 68: 1, 71: 1, 22: 1, 7: 1, 101: 1, 55

In [29]:
len(universal_mappings)

251

In [3]:
util.get_universal_mapping(mappings)

NameError: name 'mappings' is not defined

In [8]:
names = ['filename1.blockdata','filename2.blockdata','filename3.blockdata','filename4.blockdata']
dims =  [(1,2,3),(4,5,6),(6,6,34),(122,23,30)]
df_blueprint = {'filenames' : names, 'dimensions' : dims}
df = pd.DataFrame(df_blueprint)
df

filenames     dimensions
0  filename1.blockdata      (1, 2, 3)
1  filename2.blockdata      (4, 5, 6)
2  filename3.blockdata     (6, 6, 34)
3  filename4.blockdata  (122, 23, 30)

In [18]:
dictionary = {'first': 1, "second": 2, "third": 3}
vals = dictionary.values()
list(vals)[0]

1

In [5]:
ones = np.ones((1,2,3))
ones.shape[0]

1

In [3]:
np.unique(np.array([[0,1,2,3],[2,3,4,54],[2344,112,122,2]]))

array([   0,    1,    2,    3,    4,   54,  112,  122, 2344])

In [23]:
file = SchematicFile.load('./data/schematics/11265.schematic')
X = file['Schematic']['Length']
Y = file['Schematic']['Height']
Z = file['Schematic']['Width']

print(file['Schematic']['SchematicaMapping'])

blocks = file.blocks

print(X, " ", Y, " ", Z)
# for x in range(X):
#     for y in range(Y):
#         for z in range(Z):
#             print( np.uint8((blocks[y,z,x])))


Compound({'minecraft:crafting_table': Short(58), 'minecraft:netherrack': Short(87), 'minecraft:lever': Short(69), 'minecraft:bone_block': Short(216), 'minecraft:yellow_shulker_box': Short(223), 'minecraft:wooden_button': Short(143), 'minecraft:dark_oak_stairs': Short(164), 'minecraft:quartz_block': Short(155), 'minecraft:coal_ore': Short(16), 'minecraft:furnace': Short(61), 'minecraft:water': Short(9), 'minecraft:hopper': Short(154), 'minecraft:planks': Short(5), 'minecraft:air': Short(0), 'minecraft:grass': Short(2), 'minecraft:oak_stairs': Short(53), 'minecraft:magma': Short(213), 'minecraft:standing_sign': Short(63), 'minecraft:torch': Short(50), 'minecraft:log2': Short(162), 'minecraft:log': Short(17), 'minecraft:quartz_stairs': Short(156), 'minecraft:wooden_door': Short(64), 'minecraft:brick_block': Short(45), 'minecraft:double_stone_slab': Short(43), 'minecraft:pumpkin': Short(86), 'minecraft:dark_oak_door': Short(197), 'minecraft:bookshelf': Short(47), 'minecraft:cobblestone': S

In [29]:
np.uint16(-255)

C:\Users\hmhor\AppData\Local\Temp\ipykernel_18484\3118054274.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -255 to uint16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.uint16(-255)


65281

In [4]:
import schemfio
import numpy as np
schemfio.write_ndarray(np.array(np.ones((3,3,3)), dtype=np.uint16),'./', "test1.tkn")

wrote test1.tkn to ./


True

In [8]:
import schemfio
df = schemfio.load_tokenized_schems('./data/schematics_tokenized/preliminary_dataset/')
df.dimensions.apply(lambda x: tuple(eval(x))).tolist()
# df.dimensions.dtype

[(61, 20, 44),
 (75, 41, 75),
 (2, 49, 59),
 (2, 46, 36),
 (36, 36, 13),
 (17, 12, 26),
 (84, 116, 70),
 (61, 66, 162),
 (19, 20, 13),
 (28, 27, 24),
 (15, 18, 13),
 (11, 11, 15),
 (19, 14, 19),
 (158, 44, 112),
 (63, 19, 62),
 (20, 26, 18),
 (7, 4, 10),
 (87, 36, 59),
 (1, 83, 62),
 (35, 19, 30),
 (36, 32, 39),
 (13, 11, 14),
 (24, 29, 22),
 (67, 46, 36),
 (23, 28, 14),
 (19, 13, 13),
 (10, 12, 9),
 (18, 27, 17),
 (23, 18, 23),
 (67, 145, 67),
 (15, 15, 14),
 (43, 21, 32),
 (15, 14, 15),
 (57, 20, 48),
 (26, 19, 15),
 (313, 89, 431),
 (11, 16, 15),
 (25, 13, 13),
 (15, 18, 27),
 (17, 11, 16),
 (7, 6, 7),
 (21, 4, 18),
 (12, 10, 16),
 (12, 14, 32),
 (3, 29, 5),
 (37, 30, 26),
 (10, 3, 5),
 (5, 31, 43),
 (100, 51, 166),
 (390, 174, 375),
 (20, 20, 24),
 (14, 25, 14),
 (38, 27, 19),
 (11, 10, 11),
 (3, 37, 18),
 (115, 185, 125),
 (19, 19, 19),
 (11, 5, 11),
 (21, 21, 17),
 (23, 11, 28),
 (57, 39, 65),
 (47, 28, 27),
 (17, 12, 33),
 (22, 20, 24),
 (11, 10, 10),
 (81, 27, 63),
 (37, 13, 37

In [2]:
import numpy as np

def ndarray_to_bytes(arr: np.ndarray):
    bin = bytes()
    dims = arr.shape
    n_dims = len(dims)
    print(dims)
    bin = bin + np.uint8(n_dims).tobytes()
    
    return bin
    




ndarray_to_bytes(np.ones((1,3), dtype=np.uint8))

(1, 3)


b'\x02'

In [29]:
class BinaryBuilder:
    def __init__(self, bytes_: bytes = None):
        if bytes_ is None: self.bytes = bytes() 
        else: self.bytes = bytes_
        self.index = 0
        self._byte_list = self.bytes.split()
        # self.length =
    def next(self):
        # self.bytes.
        pass
    def __getitem__(self, items):
        pass 
    def __add__(self, other: bytes):
        pass
    def __iadd__(self, other: bytes):
        pass
    def __str__(self):
        return str(self.bytes)
    

test = bytes(np.ones((3,3,3), dtype=np.uint8))
test1 = b'GFG' 
test1 += b'HGH'
test1

b'GFGHGH'

In [153]:
import functools
# dtype_obj = np.dtype(np.int8).num
# print(dtype_obj)
# np.sctypeDict
arr = np.ones((3,3,3), dtype=np.uint16)

ndims = np.uint8(len(arr.shape))                       #num dims stored in 1 byte
dims = [np.uint32(arr.shape[i]).tobytes() for i in range(ndims)] #dims stores in 4 bytes each
dtype = np.uint8(arr.dtype.num)
arr_bytes = arr.tobytes()

print(ndims.tobytes())
print(dims)
print(dtype.tobytes())
print(arr_bytes)

all_bytes = bytes()

all_bytes += dtype
all_bytes += ndims
for dim in dims: all_bytes += dim
all_bytes += arr_bytes

print(np.sctypeDict[all_bytes[0]])
print(all_bytes[1])
ndims = all_bytes[1]
lst = np.frombuffer(all_bytes[2:14], dtype=np.uint32).tolist()
result = functools.reduce(lambda x, y: x * y, lst)
result
# dims = (np.uint32(all_bytes[(i * 4) + 2: (i * 4) + 6]) for i in range(ndims))
# dims

b'\x03'
[b'\x03\x00\x00\x00', b'\x03\x00\x00\x00', b'\x03\x00\x00\x00']
b'\x04'
b'\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01\x00'
<class 'numpy.uint16'>
3


27

In [75]:
from functools import reduce
def save_ndarray(arr: np.ndarray, path) -> bytes:
    dtype = np.uint8(arr.dtype.num)                                         #dtype stored in 1 byte
    ndims = np.uint8(len(arr.shape))                                        #num dims stored in 1 byte
    dims = np.array([arr.shape[i] for i in range(ndims)], dtype=np.uint32)  #dims stores in 4 bytes each
    
    file_bytes = bytes()
    file_bytes += dtype.tobytes()
    file_bytes += ndims.tobytes()
    file_bytes += dims.tobytes()
    file_bytes += arr.tobytes()
    
    with open(path, 'wb') as file:
        file.write(file_bytes)
    
def load_ndarray(path: str) -> np.ndarray:
    with open(path, 'rb') as file:
        all_bytes = file.read()
        
    dtype = np.sctypeDict[np.frombuffer(all_bytes[0:1], np.uint8)[0]]
    ndims = np.frombuffer(all_bytes[1:2], np.uint8)[0]
    arr_start_idx = 2 + (ndims * np.dtype(np.uint32).itemsize)
    dims = np.frombuffer(all_bytes[2:arr_start_idx], np.uint32)

    size = reduce(lambda x, y: x * y, dims) * np.dtype(dtype).itemsize
    arr = np.frombuffer(all_bytes[arr_start_idx: arr_start_idx + size], dtype=dtype)
    arr.resize(dims)
    return arr

In [16]:
import numpy as np
import schemfio
#demonstration of save / load ndarray working
dtype = np.uint64

random_array = np.random.randint(low=np.iinfo(dtype).min, high=np.iinfo(dtype).max, size=(3453,1023,12), dtype=dtype)

path = './arr.bin'
schemfio.save_ndarray(random_array, path)

arr_from_file = schemfio.load_ndarray(path)

if (random_array == arr_from_file).all():
    print("Arrays are equal")
else:
    print("Arrays are not equal")


Arrays are equal


In [72]:
random_array = np.random.randint(low=0, high=np.iinfo(np.uint16).max, size=(6, 5, 5), dtype=np.uint16)
random_array

array([[[59408, 34429, 15790, 28332, 36896],
        [21766, 21511, 60243, 55738, 59477],
        [14829, 12782, 58030, 56472, 28300],
        [59680,  3375, 38994, 26479, 19498],
        [  227, 12775, 49158, 45579, 58662]],

       [[30178,  7195, 19143, 32309, 28073],
        [33387, 55846,  2509, 29728, 12372],
        [60833, 46064, 62251, 57116, 58242],
        [ 1764, 51470, 40370,  8440, 65142],
        [36342, 30515, 19436, 10492, 21845]],

       [[31163, 24558,   382,  8678, 42138],
        [24353, 50549, 65466, 34166, 27283],
        [60151,  2123, 42896, 10686, 63705],
        [49432, 65399, 63592, 33052, 16085],
        [50571, 54478, 36827, 40868,  8455]],

       [[42957, 62354, 22318, 46618,   704],
        [54183, 52959, 11950, 54301, 23730],
        [ 7508, 27516, 45963,  3819, 13439],
        [60332, 23104, 30300, 21810, 63771],
        [32290, 45298, 20370, 59467, 16156]],

       [[57177, 17081, 14585,  6456,  5492],
        [ 8673, 19141, 29858, 15951, 16620],
  

In [3]:
import numpy as np
len(np.unique(np.array([0])))


1